topbar:
  homepage:
    name: 导航页
    url: https://cayzlh.github.io
  github:
    name: GitHub
    url: https://github.com/cayzlh
    target: _blank
  about:
    name: 关于
    url: /about

menu:
  Home:
    url: /
    name: 首页
  Archives:
    url: /archives
    name: 归档
  Tools:
    url: /
    name: 在线工具
    children:
      - name: Json在线工具
        url: https://cayzlh.github.io/tools/online-JSONFormat/
      - name: Markdown在线转换工具
        url: https://cayzlh.github.io/tools/online-markdown/

jumbotron:
  slogan: 记录成长路上的风景
  infos:
    - name: 富强
      url: /
    - name: 民主
      url: /
    - name: 文明
      url: /
    - name: 和谐
      url: /
    - name: 自由
      url: /
    - name: 平等
      url: /
    - name: 公正
      url: /
    - name: 法制
      url: /
    - name: 爱国
      url: /
    - name: 敬业
      url: /
    - name: 诚信
      url: /
    - name: 友善
      url: /

social:
  - url: https://github.com/cayzlh
    target: _blank
    icon: fa-github
    txt:
  - url: https://twitter.com/Q2F5emxo
    target: _blank
    icon: fa-twitter
    txt:
  - url: mailto:chenanyu@cayzlh.com
    target: _blank
    icon:
    txt: 邮

favicon: /favicon.svg

# 展示精选文章, 需在文章中添加 favorite: true 属性
favorites:
  enable: true # 是否展示精选文章
  title: 精选文章 # 标题
  num: 6  # 展示多少个， 建议不要太多

# 展示开源项目（GitHub）
openSource:
  enable: false
  title: 开源软件
  username: cayzlh # github用户名，用于展示stars 和 forks数
  repos:
    - url: https://github.com/cayzlh/cayzlh-starters
      name: cayzlh-starters # repo的名称，一定要填对
      title: cayzlh-starters # 展示到页面的名称
      description: 由个人封装的一些springboot starter项目
    - url: https://github.com/cayzlh/cayzlh.github.io
      name: cayzlh.github.io
      title: cayzlh.github.io
      description: 个人导航页

# 是否白嫖cdn加速，本地调试样式之类的记得设置成false
jsDelivr:
  enable: true
  url: https://cdn.jsdelivr.net/gh/cayzlh/blog@master

google:
  analytics:
    enable: true
    id: UA-129095667-1
  verification:
    enable: true
    id: VrcbMTVpFGlHkIERHBt753dAtXKF4qirjnDweuXSRJw

ICP: # 京ICP备123456789号

top:
  enable: true # 是否开启回到最上面

rss:
  enable: true

archive:
  title: All My Blogs
  subtitle: Record the scenery on the road of growth

# 分类页面设置，用于指定分类页的元素的展示
category:
  enable: false
  Git: # 每个Key要写对应分类的名称
    title: Git相关文章
    subtitle: git操作相关的文章

copyright:
  enable: true
  name: Q2F5emxo
  since: 2020
